# ---------- STAGE 1 ----------
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
COPY .env.production .env
RUN npm run build

# ---------- STAGE 2 ----------
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /path/to/nginx/config/conf.d