# Stage 1: Build the Spring Boot app
FROM maven:3.9-eclipse-temurin-21 AS build


WORKDIR /app


COPY pom.xml .
RUN mvn dependency:go-offline -B


COPY src ./src

RUN mvn clean package -DskipTests


# Stage 2: Run the Spring Boot app
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE some_port


ENTRYPOINT ["java", "-jar", "app.jar"]
