spring.application.name=AhedDatabase
server.port= ${SERVER_PORT}
server.servlet.context-path=/api
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
app.secret-key = ${SECRET_KEY}
spring.jackson.deserialization.accept-empty-string-as-null-object= true