
!------ API config
spring.application.name=AhedDatabase
server.port= ${BACKEND_SERVER_PORT}
server.servlet.context-path=${CONTEXT_PATH}
spring.jackson.deserialization.accept-empty-string-as-null-object= true

!------ DB config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto= ${HIBERNATE}


!------ deployment specific
app.secret-key = ${SECRET_KEY}
app.domain-URL = ${DOMAIN_URL}
app.my-mail = ${MY_MAIL}


!------ SMTP config
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true